export const IPC_CHANNELS = {
    APP_PING: 'noa:app:ping',
    APP_GET_VERSIONS: 'noa:app:getVersions',
    WINDOW_MINIMIZE: 'noa:window:minimize',
    WINDOW_TOGGLE_MAXIMIZE: 'noa:window:toggleMaximize',
    WINDOW_CLOSE: 'noa:window:close',
    WINDOW_CLOSE_INTENT: 'noa:window:closeIntent',
    ASSET_SAVE_CAPTURE: 'noa:asset:saveCapture',
    ASSET_LIST: 'noa:asset:list',
    ASSET_OPEN_IN_FOLDER: 'noa:asset:openInFolder',
    ASSET_DELETE: 'noa:asset:delete',
    OCR_RECOGNIZE_ASSET: 'noa:ocr:recognizeAsset',
    MEDIA_PICK_LOCAL_VIDEOS: 'noa:media:pickLocalVideos',
    MEDIA_REGISTER_HEADERS: 'noa:media:registerHeaders',
    NOTES_GET_TEMP_PROJECT: 'noa:notes:getTempProject',
    NOTES_SAVE_TEMP_PROJECT: 'noa:notes:saveTempProject',
    NOTES_SET_DIRTY: 'noa:notes:setDirty',
    NOTES_SET_PROJECT_VIDEOS: 'noa:notes:setProjectVideos',
    NOTES_SAVE_PROJECT_AS: 'noa:notes:saveProjectAs',
    NOTES_LIST_SAVE_DIRECTORIES: 'noa:notes:listSaveDirectories',
    NOTES_CREATE_SAVE_DIRECTORY: 'noa:notes:createSaveDirectory',
    EXPORT_SESSION: 'noa:export:session',
    NOTES_EXPORT_MARKDOWN: 'noa:notes:exportMarkdown',
};
